Repository chacha912/coupang-signin, pull requests merged in 2021-08, with the labels that each got.

#13 Loginform markup 완료
  src/assets/arrow.svg
  src/components/A11yHidden/A11yHidden.css
  src/components/A11yHidden/A11yHidden.js
  src/components/Input/Input.module.scss
  src/components/index.js
  src/containers/LoginForm/LoginForm.js
  src/containers/LoginForm/LoginForm.module.scss
  src/index.js
  src/pages/SignIn/SignIn.js
Labels: 🎨 html&css

#16 뷰에서 자동로그인이 체크 되도록 수정하기
  src/containers/LoginForm/LoginForm.js
Labels: ✨ Feature

#18 Login input 유효성 검사
  src/components/IconInput/IconInput.js
  src/components/Input/Input.js
  src/containers/LoginForm/LoginForm.js
Labels: ✨ Feature

#17 initialize Loginform.storybook.js
  src/containers/LoginForm/LoginFrom.stories.js
Labels: ✅ test

#19 로그인폼 입력상태, 오류상태 스토리 추가
  src/containers/LoginForm/LoginForm.js
  src/containers/LoginForm/LoginForm.module.scss
  src/containers/LoginForm/LoginFrom.stories.js
Labels: ✅ test
